# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

channels:
  - conda-forge
  - scipp
  - nodefaults
dependencies:
  - python==3.10.*
  - pip
  - websockify
  - pyaml
  - corner
  - dynesty
  - emcee
  - h5py
  - ipympl
  - ipython
  - ipywidgets
  - ipykernel
  - jupyter-book
  - matplotlib
  - mpltoolbox
  - numpy
  - pip
  - plopp==23.08.0
  - pooch
  - python-graphviz
  - pythreejs
  - scipp==23.07.0
  - scippneutron==23.04.0
  - scippnexus==23.07.0
  - scipy
  - sphinxcontrib-mermaid
  - tqdm
  - jupyter-server-proxy>=1.4
  - ply
  - matplotlib
  - numpy
  - tornado
  - scipy
  - pillow
  - pyqtgraph
  - pyqt
  - qscintilla2
  - nexpy
  - scitacean
  - pip:
      - jupyterquiz
      - easysciencecore
      - McStasScript
      - guide_bot
      - nbgitpuller
      - sasmodels
      - sasdata
      - bumps
      - .
