other:
  characters_per_line: 85
paths:
  mcrun_path: /usr/share/mcstas/2.7/bin/
  mcstas_path: /usr/share/mcstas/2.7/
  mcxtrace_path: /usr/share/mcxtrace/1.6/
  mxrun_path: /usr/share/mcxtrace/1.6/bin/
